#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed May 20 15:53:55 EDT 2020
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim SysArray_tb_behav -key {Behavioral:sim_1:Functional:SysArray_tb} -tclbatch SysArray_tb.tcl -view /home/ld443/workspace_debug/sys_128/vivado_rtl_kernel/SysArray_ex/waveform.wcfg -log simulate.log -sv_seed 1"
xsim SysArray_tb_behav -key {Behavioral:sim_1:Functional:SysArray_tb} -tclbatch SysArray_tb.tcl -view /home/ld443/workspace_debug/sys_128/vivado_rtl_kernel/SysArray_ex/waveform.wcfg -log simulate.log -sv_seed 1

